
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


# Text to speech
tts:
  - platform: google_translate
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
cloud:

switch: !include_dir_merge_list switchs/


automation split: !include_dir_list ./automations/
alarm_control_panel:
  - platform: manual
    name: home_alarm
    code: !secret alarm_code
    arming_time: 2
    delay_time: 60
    
ios:
